---
name: CI

'on':
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install python dependencies.
        run: pip3 install molecule docker yamllint ansible-lint "Jinja2<3.1" molecule-docker molecule-vagrant
      - name: Install ansible dependencies.
        run: ansible-galaxy collection install community.docker
      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
